import type { WorldData, GameSettings, StarSystem, Destination, JumpRoute, JumpDrive, StoryBeat } from './types';

export const WORLD: WorldData = {
  settings: {
    player: { name: 'Captain', startingCredits: 100 },
    startingLocation: { system: 'sol', destination: 'elysium-station' },
  },
  systems: [
    {
      id: 'sol',
      name: 'Sol',
      starType: 'G2V',
      distanceFromSol: 0.0,
      zone: 'core',
      security: 'high',
      population: 'massive',
      dangerLevel: 'low',
      playerKnowledge: 'public',
      economy: ['industrial', 'administrative', 'military'],
      majorFactions: ['terran-union', 'helios-directorate'],
      destinations: ['elysium-station', 'galileo-transfer', 'tycho-orbital', 'mars-anchor'],
      tags: ['core-world', 'restricted', 'high-traffic'],
      description: 'The birthplace of humanity and the political heart of known space.',
    },
    {
      id: 'alpha-centauri',
      name: 'Alpha Centauri',
      starType: 'G2V / K1V',
      distanceFromSol: 4.3,
      zone: 'core',
      security: 'high',
      population: 'high',
      dangerLevel: 'low',
      playerKnowledge: 'public',
      economy: ['trade', 'shipping', 'finance'],
      majorFactions: ['centauri-trade-league', 'terran-union'],
      destinations: ['new-horizon-port', 'hestia-ring'],
      tags: ['trade-hub', 'wealthy', 'stable'],
      description: 'The commercial crossroads of nearby human space.',
    },
    {
      id: 'barnards-star',
      name: "Barnard's Star",
      starType: 'M4V',
      distanceFromSol: 5.9,
      zone: 'frontier',
      security: 'medium',
      population: 'medium',
      dangerLevel: 'medium',
      playerKnowledge: 'public',
      economy: ['mining', 'refining', 'fuel-production'],
      majorFactions: ['independent-miners-guild'],
      destinations: ['redline-station', 'kepler-yard'],
      tags: ['mining', 'frontier-edge', 'working-class'],
      description: 'Primary resource supplier for the Core Systems, dominated by the Independent Miners Guild.',
    },
    {
      id: 'wolf-359',
      name: 'Wolf 359',
      starType: 'M6V',
      distanceFromSol: 7.9,
      zone: 'frontier',
      security: 'low',
      population: 'low',
      dangerLevel: 'high',
      playerKnowledge: 'public',
      economy: ['salvage', 'black-market', 'scavenging'],
      majorFactions: ['free-captains', 'grey-market-cartel'],
      destinations: ['drift-market', 'blackwake-yard'],
      tags: ['lawless', 'salvage', 'pirate-activity'],
      description: 'On the edge of regulated space, attracting scavengers, smugglers and opportunists.',
    },
  ],

  destinations: [
    {
      id: 'elysium-station',
      name: 'Elysium Station',
      system: 'sol',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: true, missionBoard: true, shipRepair: true, fuel: true, shipDealer: false },
      npcs: { trader: 'Merchant Kess' },
      goodsBias: ['administrative', 'trade'],
      dangerLevel: 'low',
      tags: ['starter', 'mid-orbit', 'relaxed-docking'],
      description: 'A mid-sized civilian port in Earth orbit, popular with independent pilots.',
    },
    {
      id: 'galileo-transfer',
      name: 'Galileo Transfer Hub',
      system: 'sol',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: true, missionBoard: true, shipRepair: false, fuel: true, shipDealer: false },
      npcs: { trader: 'Broker Valdis' },
      goodsBias: ['industrial', 'administrative', 'military'],
      dangerLevel: 'low',
      tags: ['busy', 'corporate', 'high-traffic'],
      description: 'Primary civilian transport interchange between Earth and the outer system.',
    },
    {
      id: 'tycho-orbital',
      name: 'Tycho Orbital',
      system: 'sol',
      locationType: 'orbital',
      type: 'military',
      amenities: { trader: false, missionBoard: true, shipRepair: true, fuel: true, shipDealer: false },
      npcs: {},
      goodsBias: ['military', 'industrial'],
      dangerLevel: 'low',
      tags: ['restricted', 'military', 'licensed-only'],
      description: 'Military-aligned logistics and repair station in lunar orbit.',
    },
    {
      id: 'mars-anchor',
      name: 'Mars Anchor',
      system: 'sol',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: true, missionBoard: false, shipRepair: true, fuel: true, shipDealer: true },
      npcs: { trader: 'Factor Orin' },
      goodsBias: ['industrial', 'military'],
      dangerLevel: 'low',
      tags: ['heavy-industry', 'bulk-freight', 'ship-market'],
      description: 'Heavy-lift platform anchored above the Martian equator for bulk ore and component transfers.',
    },
    {
      id: 'new-horizon-port',
      name: 'New Horizon Port',
      system: 'alpha-centauri',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: true, missionBoard: true, shipRepair: true, fuel: true, shipDealer: true },
      npcs: { trader: 'Syndic Marelle' },
      goodsBias: ['trade', 'finance', 'shipping'],
      dangerLevel: 'low',
      tags: ['trade-hub', 'wealthy', 'finance-district'],
      description: "The system's primary trade and passenger hub, headquarters of the Centauri Trade League.",
    },
    {
      id: 'hestia-ring',
      name: 'Hestia Ring',
      system: 'alpha-centauri',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: true, missionBoard: true, shipRepair: true, fuel: true, shipDealer: false },
      npcs: { trader: 'Runner Cho' },
      goodsBias: ['shipping', 'trade'],
      dangerLevel: 'low',
      tags: ['fast-turnaround', 'volume-trade'],
      description: 'Large-scale civilian docking structure known for rapid turnaround and low docking fees.',
    },
    {
      id: 'redline-station',
      name: 'Redline Station',
      system: 'barnards-star',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: true, missionBoard: true, shipRepair: true, fuel: true, shipDealer: false },
      npcs: { trader: 'Smelter Haag' },
      goodsBias: ['mining', 'refining', 'fuel-production'],
      dangerLevel: 'medium',
      tags: ['industrial', 'ore-market', 'three-shift'],
      description: 'Massive rotating refinery and trade dock servicing mining traffic around the clock.',
    },
    {
      id: 'kepler-yard',
      name: 'Kepler Yard',
      system: 'barnards-star',
      locationType: 'orbital',
      type: 'civilian',
      amenities: { trader: false, missionBoard: true, shipRepair: true, fuel: true, shipDealer: true },
      npcs: {},
      goodsBias: ['mining', 'salvage'],
      dangerLevel: 'medium',
      tags: ['shipbreaking', 'salvage', 'cheap-repairs', 'questionable-standards'],
      description: 'Shipbreaking and salvage facility famous for cheap repairs and questionable engineering standards.',
    },
    {
      id: 'drift-market',
      name: 'Drift Market',
      system: 'wolf-359',
      locationType: 'orbital',
      type: 'black-market',
      amenities: { trader: true, missionBoard: true, shipRepair: true, fuel: true, shipDealer: true },
      npcs: { trader: 'The Quartermaster' },
      goodsBias: ['salvage', 'black-market', 'scavenging'],
      dangerLevel: 'high',
      tags: ['lawless', 'no-questions-asked', 'contraband'],
      description: 'A sprawling patchwork station assembled from salvaged hull sections where almost anything can be purchased.',
    },
    {
      id: 'blackwake-yard',
      name: 'Blackwake Yard',
      system: 'wolf-359',
      locationType: 'orbital',
      type: 'black-market',
      amenities: { trader: false, missionBoard: false, shipRepair: true, fuel: true, shipDealer: false },
      npcs: {},
      goodsBias: ['salvage', 'black-market'],
      dangerLevel: 'high',
      tags: ['illegal-mods', 'cartel-security', 'off-registry'],
      description: 'Illegal modification facility specialising in reactor tampering and military surplus retrofits.',
    },
  ],

  routes: [
    { from: 'sol', to: 'alpha-centauri', distance: 4.3, stability: 'stable', security: 'high' },
    { from: 'sol', to: 'barnards-star', distance: 5.9, stability: 'stable', security: 'medium' },
    { from: 'sol', to: 'wolf-359', distance: 7.9, stability: 'unstable', security: 'low' },
    { from: 'alpha-centauri', to: 'barnards-star', distance: 4.1, stability: 'stable', security: 'medium' },
    { from: 'barnards-star', to: 'wolf-359', distance: 3.1, stability: 'unstable', security: 'low' },
  ],

  drives: [
    { id: 'civilian-mk1', name: 'Civilian Mk1', maxDistanceLy: 4, fuelEfficiency: 0.8, cost: 10000 },
    { id: 'civilian-mk2', name: 'Civilian Mk2', maxDistanceLy: 7, fuelEfficiency: 0.6, cost: 20000 },
    { id: 'hauler', name: 'Hauler', maxDistanceLy: 12, fuelEfficiency: 0.95, cost: 50000 },
    { id: 'explorer', name: 'Explorer', maxDistanceLy: 20, fuelEfficiency: 0.85, cost: 100000 },
  ],

  ships: [
    {
      id: 'freighter',
      name: 'Standard Freighter',
      class: 'freighter',
      cost: 5000,
      cargoCapacityKg: 2000,
      fuelCapacityL: 100,
      hullPoints: 60,
      defaultJumpDrive: 'civilian-mk1',
      tags: ['starter', 'slow', 'reliable'],
      description: 'The workhorse of civilian space — underpowered, overloaded, and still flying.',
    },
    {
      id: 'scout',
      name: 'Scout Runner',
      class: 'scout',
      cost: 25000,
      cargoCapacityKg: 500,
      fuelCapacityL: 80,
      hullPoints: 40,
      defaultJumpDrive: 'civilian-mk2',
      tags: ['fast', 'exploration', 'low-cargo'],
      description: 'Built for speed and range, not cargo — excels at charting new routes and courier jobs.',
    },
    {
      id: 'hauler',
      name: 'Deep Hauler',
      class: 'hauler',
      cost: 80000,
      cargoCapacityKg: 8000,
      fuelCapacityL: 200,
      hullPoints: 100,
      defaultJumpDrive: 'hauler',
      tags: ['high-cargo', 'durable', 'trade-optimised'],
      description: "The serious trader's ship — enormous cargo capacity for bulk runs between Core and frontier.",
    },
  ],

  factions: [
    {
      id: 'terran-union',
      name: 'Terran Union',
      type: 'government',
      homeSystem: 'sol',
      size: 'large',
      influence: ['sol', 'alpha-centauri', 'barnards-star'],
      tags: ['bureaucratic', 'military', 'regulated', 'law-enforcement'],
      description: 'The dominant government of human space, maintaining strict jurisdiction over Core orbital infrastructure.',
    },
    {
      id: 'helios-directorate',
      name: 'Helios Directorate',
      type: 'corporation',
      homeSystem: 'sol',
      size: 'large',
      influence: ['sol', 'alpha-centauri'],
      tags: ['energy', 'fuel-monopoly', 'political', 'corporate'],
      description: 'Powerful corporation holding significant influence over energy and fuel distribution contracts.',
    },
    {
      id: 'centauri-trade-league',
      name: 'Centauri Trade League',
      type: 'corporation',
      homeSystem: 'alpha-centauri',
      size: 'large',
      influence: ['alpha-centauri', 'sol', 'barnards-star'],
      tags: ['trade', 'finance', 'arbitration', 'neutral'],
      description: 'Controls commercial licensing across Alpha Centauri; its markets set commodity prices across dozens of systems.',
    },
    {
      id: 'independent-miners-guild',
      name: 'Independent Miners Guild',
      type: 'guild',
      homeSystem: 'barnards-star',
      size: 'medium',
      influence: ['barnards-star'],
      tags: ['mining', 'labour', 'self-governing', 'frontier'],
      description: "Self-governing labour organisation holding extraction rights across Barnard's Belt.",
    },
    {
      id: 'free-captains',
      name: 'Free Captains',
      type: 'independent',
      homeSystem: 'wolf-359',
      size: 'medium',
      influence: ['wolf-359', 'barnards-star'],
      tags: ['piracy', 'salvage', 'democratic', 'frontier'],
      description: 'Loose democratic council of independent operators in Wolf 359.',
    },
    {
      id: 'grey-market-cartel',
      name: 'Grey Market Cartel',
      type: 'criminal',
      homeSystem: 'wolf-359',
      size: 'medium',
      influence: ['wolf-359'],
      tags: ['criminal', 'smuggling', 'contraband', 'violent'],
      description: "De facto controllers of Wolf 359's two stations, running protection rackets and contraband networks.",
    },
  ],

  commodities: [
    {
      id: 'iron-ore',
      name: 'Iron Ore',
      basePrice: 80,
      category: 'raw-material',
      legal: true,
      weightKg: 10,
      description: 'Unrefined iron extracted from asteroid fields and planetary crust.',
    },
    {
      id: 'rare-earth',
      name: 'Rare Earth Elements',
      basePrice: 400,
      category: 'raw-material',
      legal: true,
      weightKg: 5,
      description: 'High-value minerals essential for electronics and drive components.',
    },
    {
      id: 'deuterium',
      name: 'Deuterium Crystals',
      basePrice: 200,
      category: 'raw-material',
      legal: true,
      weightKg: 3,
      description: 'Refined hydrogen isotope used in jump drive fuel production.',
    },
    {
      id: 'refined-metals',
      name: 'Refined Metals',
      basePrice: 220,
      category: 'manufactured',
      legal: true,
      weightKg: 8,
      description: 'Processed alloys ready for ship construction and infrastructure work.',
    },
    {
      id: 'ship-components',
      name: 'Ship Components',
      basePrice: 650,
      category: 'manufactured',
      legal: true,
      weightKg: 15,
      description: 'Drive housings, hull panels, sensor arrays — standard replacement parts.',
    },
    {
      id: 'electronics',
      name: 'Consumer Electronics',
      basePrice: 500,
      category: 'manufactured',
      legal: true,
      weightKg: 2,
      description: 'Commercial-grade devices popular across populated stations.',
    },
    {
      id: 'rations',
      name: 'Ration Packs',
      basePrice: 60,
      category: 'consumable',
      legal: true,
      weightKg: 1,
      description: 'Bulk-packaged food supplies for crew and colony populations.',
    },
    {
      id: 'medical-supplies',
      name: 'Medical Supplies',
      basePrice: 350,
      category: 'consumable',
      legal: true,
      weightKg: 2,
      description: 'Pharmaceuticals, surgical kits and diagnostic equipment.',
    },
    {
      id: 'fuel-cells',
      name: 'Fuel Cells',
      basePrice: 180,
      category: 'consumable',
      legal: true,
      weightKg: 4,
      description: 'Pre-charged energy cells for ship systems and surface equipment.',
    },
    {
      id: 'combat-stims',
      name: 'Combat Stimulants',
      basePrice: 900,
      category: 'contraband',
      legal: false,
      weightKg: 1,
      description: 'Performance-enhancing compounds banned under Union health codes.',
    },
    {
      id: 'black-box-data',
      name: 'Black Box Data',
      basePrice: 1500,
      category: 'contraband',
      legal: false,
      weightKg: 1,
      description: 'Encrypted nav logs and sensor recordings from destroyed vessels.',
    },
    {
      id: 'grey-market-tech',
      name: 'Grey Market Tech',
      basePrice: 1200,
      category: 'contraband',
      legal: false,
      weightKg: 3,
      description: 'Unlicensed ship modifications — transponder masks, reactor overrides.',
    },
  ],

  storyBeats: [
    {
      id: 'opening-arrival',
      title: 'Opening Arrival at Elysium Station',
      trigger: 'game-start',
      type: 'intro',
      location: 'elysium-station',
      skippable: true,
      playerKnowledge: 'public',
      text: 'YEAR  2284\n\nThe war ended six years ago.\n\nThe corporations divided the wreckage between them\nand called it peace.\n\nYou were a Union pilot once. Now you haul freight\nbetween stations that barely remember your name.\n\nYour ship drifted into Elysium Station an hour ago,\nlow on fuel and lower on credits.\n\nThe galaxy doesn\'t care.\n\nNeither, you\'ve decided, do you.\n\nTime to find work.',
    },
    {
      id: 'first-jump',
      title: 'First Jump — Leaving Sol',
      trigger: 'first-jump',
      type: 'discovery',
      skippable: true,
      playerKnowledge: 'public',
      text: 'The jump drive spins up. The station shrinks.\n\nSol\'s light vanishes behind a wall of compressed space.\n\nFor a moment there is nothing — no sound, no direction,\nno sense of being anywhere at all.\n\nThen the stars snap back.\n\nYou are somewhere new.',
    },
    {
      id: 'enter-wolf-359',
      title: 'First Entry — Wolf 359',
      trigger: 'system-enter:wolf-359',
      type: 'system-enter',
      location: 'wolf-359',
      skippable: true,
      playerKnowledge: 'public',
      text: 'Your nav system flags the system before you\'ve cleared\nthe jump corridor.\n\nSECURITY ADVISORY: WOLF 359\nNo patrol coverage. Travel at own risk.\n\nThe Drift Market beacon is already pinging you.\nSomeone always knows when a new ship arrives here.\n\nKeep your hand near the controls.',
    },
  ],
};

export function getSystem(id: string): StarSystem | undefined {
  return WORLD.systems.find(s => s.id === id);
}

export function getDestination(id: string): Destination | undefined {
  return WORLD.destinations.find(d => d.id === id);
}

export function getRoutesFrom(systemId: string): JumpRoute[] {
  return WORLD.routes.filter(r => r.from === systemId || r.to === systemId);
}

export function getDrive(id: string): JumpDrive | undefined {
  return WORLD.drives.find(d => d.id === id);
}

export function getStoryBeat(id: string): StoryBeat | undefined {
  return WORLD.storyBeats.find(b => b.id === id);
}

export function getStoryBeatsByTrigger(trigger: string): StoryBeat[] {
  return WORLD.storyBeats.filter(b => b.trigger === trigger);
}

export function getGameSettings(): GameSettings {
  return WORLD.settings;
}
